graphql-brasil/empresas-que-usam-graphql-no-brasil

MOBILE.md
PULL_REQUEST_TEMPLATE.md
README.md

feat: add vntrx.com

---

MOBILE.md
README.md

Add KeepClear

---

MOBILE.md
README.md

Adiciona Wedy a lista

---

MOBILE.md
README.md

Add: Casa Magalhães

---

MOBILE.md
README.md

Add Fundação CERTI

---

MOBILE.md
README.md

Added Softplan

---

MOBILE.md
README.md

add StartSe company in  Readme

---

MOBILE.md
README.md

Add DevGrid

---

MOBILE.md
README.md

Add Cotabox to the list

---

MOBILE.md
README.md

Adicionando Nexo à lista

---

README.md

add cubo.network

---

MOBILE.md
README.md

Add Liferay

---

MOBILE.md
README.md

Add Ignição Digital

---

MOBILE.md

add cubo.network on mobile

---

MOBILE.md
README.md

Add Voltbras

---

MOBILE.md
README.md

add Ochain

---

MOBILE.md
README.md

Add Caju Benefícios

---

MOBILE.md
README.md

adicionado duas novas empresas

---

MOBILE.md
README.md

Inserindo a Rethink

---

MOBILE.md
README.md

Adicionei o projeto da [Fábrica de Software](https://github.com/fabsoftwareifrs) do [IFRS](https://ifrs.edu.br/)!
O projeto Fábrica de Software é um grupo de bolsistas e voluntários que desenvolvem aplicações open source para a educação utilizando a Stack Node e GraphQL o atual projeto é o desenvolvimento de um Software de Gestão de Biblioteca ILS (Integrated Library System) que será open source e utilizará GraphQL, além de projetos futuros que serão desenvolvidos na Stack!
Atualmente temos apenas a descrição da tarefa de entrada no projeto e um quickstart de node com GraphQL, mas iremos postar o Sistema de Bibliotecas em breve e os futuros projetos assim que eles forem sendo desenvolvidos!
Contribuições e participação aos …

Adicionei o projeto da Fábrica de Software do IFRS

---

MOBILE.md
README.md

Adiciona Quóro ao readme

---

MOBILE.md
README.md

Adicionando Volanty

---

MOBILE.md
README.md

Adicionando PagSeguro

---

MOBILE.md
README.md

add Cuidas

---

MOBILE.md
README.md

feat: add oito.work

---

MOBILE.md
README.md

adding Enext

---

MOBILE.md
README.md

Add Riderize App

---

MOBILE.md
README.md

adding corebiz

---

README.md

Woovi is a startup for change the form of payments.

Adding Woovi in list

---

MOBILE.md

Adding Woovi in List Mobile
